/* ==================================
   TRANSITCARE CHATBOT
   Multilingual: English + Hindi/Marathi Roman input/output
   ================================== */
function toggleChatbot(){const w=document.getElementById("chatbotWindow");if(!w)return;w.style.display=w.style.display==="flex"?"none":"flex";}
function addMessage(message,sender){const messages=document.getElementById("chatbotMessages");const c=document.createElement("div");c.className=sender==="bot"?"chat-message bot-message":"chat-message user-message";const b=document.createElement("div");b.className="message-bubble";b.innerHTML=message;c.appendChild(b);messages.appendChild(c);messages.scrollTop=messages.scrollHeight;}
function sendMessage(){const input=document.getElementById("chatbotInput"),message=input.value.trim();if(!message)return;addMessage(message,"user");input.value="";fetch("/chatbot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:message,language:window.getTransitCareLanguage?window.getTransitCareLanguage():"en"})}).then(r=>r.json()).then(data=>addMessage(data.reply,"bot")).catch(error=>{const lang=window.getTransitCareLanguage?window.getTransitCareLanguage():"en";addMessage(lang==="hi"?"माफ़ कीजिए, अभी कनेक्शन में समस्या है। कृपया थोड़ी देर बाद फिर कोशिश करें।":lang==="mr"?"माफ करा, सध्या कनेक्शनमध्ये अडचण आहे. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा।":"Sorry, I'm having trouble connecting right now. Please try again.","bot");console.error(error);});}
function chatbotEnter(event){if(event.key==="Enter")sendMessage();}
function quickMessage(message){document.getElementById("chatbotInput").value=message;sendMessage();}
function updateChatbotLanguage(){const t=window.getChatbotText?window.getChatbotText():null;if(!t)return;const title=document.querySelector('.chatbot-title'),status=document.querySelector('.chatbot-status'),input=document.getElementById('chatbotInput'),buttons=document.querySelectorAll('.quick-button');if(title)title.textContent=t.title;if(status)status.textContent=t.online;if(input)input.placeholder=t.placeholder;if(buttons.length>=2){if(buttons.length>=3){buttons[0].textContent=t.report;buttons[0].onclick=()=>quickMessage(window.getTransitCareLanguage()==='hi'?'mujhe ek transport problem report karni hai':window.getTransitCareLanguage()==='mr'?'mala vahatukichi samasya nondvaychi aahe':'I want to report a problem');buttons[1].textContent=t.status;buttons[2].textContent=t.care;buttons[1].onclick=()=>quickMessage(window.getTransitCareLanguage()==='hi'?'meri complaint ka status check karo':window.getTransitCareLanguage()==='mr'?'mazi takrarichi sthiti tapasa':'I want to check my complaint status');buttons[2].onclick=()=>quickMessage(window.getTransitCareLanguage()==='hi'?'mujhe customer care chahiye':window.getTransitCareLanguage()==='mr'?'mala customer care pahije':'I need customer care');}else{buttons[0].textContent=t.status;buttons[1].textContent=t.care;buttons[0].onclick=()=>quickMessage(window.getTransitCareLanguage()==='hi'?'meri complaint ka status check karo':window.getTransitCareLanguage()==='mr'?'mazi takrarichi sthiti tapasa':'I want to check my complaint status');buttons[1].onclick=()=>quickMessage(window.getTransitCareLanguage()==='hi'?'mujhe customer care chahiye':window.getTransitCareLanguage()==='mr'?'mala customer care pahije':'I need customer care');}}}
window.updateChatbotLanguage=updateChatbotLanguage;
document.addEventListener('DOMContentLoaded',()=>{updateChatbotLanguage();const t=window.getChatbotText?window.getChatbotText():null;const box=document.querySelector('#chatbotMessages .bot-message .message-bubble');if(box&&t)box.innerHTML=t.greeting;});
